# Generated by Django 3.2.5 on 2023-07-07 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("db", "0003_iborhistory_iborhistoryrequest")]

    operations = [
        migrations.AlterUniqueTogether(
            name="iborhistory",
            unique_together={("currency", "date", "term_months", "ibor_type")},
        )
    ]
