# Generated by Django 3.2.5 on 2023-07-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_alter_iborhistory_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='iborhistory',
            name='rating',
            field=models.CharField(blank=True, max_length=251, null=True),
        ),
        migrations.AlterField(
            model_name='iborhistory',
            name='term_months',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='iborhistory',
            unique_together={('currency', 'date', 'term_months', 'rating', 'ibor_type')},
        ),
    ]
