# Generated by Django 4.2.4 on 2023-08-07 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("db", "0005_auto_20230711_0847")]

    operations = [
        migrations.CreateModel(
            name="Regulation",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "doc_code",
                    models.CharField(max_length=3, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="RegulationRelation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("relation_type", models.CharField(max_length=32)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="db.regulation",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targets",
                        to="db.regulation",
                    ),
                ),
            ],
            options={"unique_together": {("source", "target", "relation_type")}},
        ),
    ]
